### ISSUE TITLE
Can assign advisor to blank advisor name

### ISSUE THREAD

**Issue by katiejiang** [hack4impact/immigrant-defense-project#50]
<img width="719" alt="screen shot 2018-11-13 at 1 43 45 pm" src="https://user-images.githubusercontent.com/7690709/48435312-2d652680-e74a-11e8-9c44-810b07ceaa08.png">

**Comment by stevenbursztyn** [comment]
whoops ok, will take a look. just to confirm, this should also change their stage right? 



--
Steven Bursztyn
Candidate for B.S.E. in Computer and Information Science
University of Pennsylvania | Class of 2020
bursztyn@seas.upenn.edu

**Comment by katiejiang** [comment]
They can't be assigned to no advisor, so this shouldn't change their stage.

**Comment by stevenbursztyn** [comment]
right but I’m saying if someone used to be assigned to an advisor, and now got unassigned (aka assigned to blank)? OR should i remove the blank option as a whole



--
Steven Bursztyn
Candidate for B.S.E. in Computer and Information Science
University of Pennsylvania | Class of 2020
bursztyn@seas.upenn.edu

**Comment by katiejiang** [comment]
OHHH I see what you're saying! Let's just remove the blank option, and add a button that unassigns them from an advisor (something like "Unmatch Advisor").

**Comment by katiejiang** [comment]
nice catch 😎

**Comment by stevenbursztyn** [comment]
Ok, so it was being weirdly complicated to add the second button. Blank unassigns advisors now and switches stages appropriately. If that's a huge issue, lmk.
